[features]
seeds = false
skip-lint = false

[programs.localnet]
setup = "35qSrLjTWNtqytQKN487v5MzRQHnd1HaPqNsChzdiK5D"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/dimas/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
