version: "3"

services:
  launcher:
    build:
      context: .
    ports:
      - "${PUBLIC_PORT}:8080"
    environment:
      - CHALLENGE_ID=${CHALLENGE_ID}
      - FLAG=${FLAG}
      - HTTP_PORT=8545
      - PROXY_PORT=8080
      - LAUNCHER_PORT=8081
      - ENV=production
      - ALLOW_RANDOM_TICKET=true
    deploy:
      resources:
        limits:
          cpus: "1.0"
