[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
setup = "GwzDES36sT6CNqWmbMe9QpfxrAinWPwHvBNBNSfA3ejg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
